export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_TRAINING_CENTER = 'GET_TRAINING_CENTER';
export const TRAINING_CENTER_LOADING = 'TRAINING_CENTER_LOADING';
export const TRAINING_CENTER_NOT_FOUND = 'TRAINING_CENTER_NOT_FOUND';
export const CLEAR_CURRENT_TRAINING_CENTER = 'CLEAR_CURRENT_TRAINING_CENTER';
export const GET_TRAINING_CENTERS = 'GET_TRAINING_CENTERS';
export const COURSE_LOADING = 'COURSE_LOADING';
// COURSES
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const UPDATE_FILTER = 'UPDATE_FILTER ';
export const GET_TRAINING_CENTER_COURSES = 'GET_TRAINING_CENTER_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';
