export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_TRAINING_CENTER = 'GET_TRAINING_CENTER';
export const TRAINING_CENTER_LOADING = 'TRAINING_CENTER_LOADING';
export const TRAINING_CENTER_NOT_FOUND = 'TRAINING_CENTER_NOT_FOUND';
export const CLEAR_CURRENT_TRAINING_CENTER = 'CLEAR_CURRENT_TRAINING_CENTER';
export const GET_TRAINING_CENTERS = 'GET_TRAINING_CENTERS';